In [3]:
import numpy as np 
import cv2
import os
input_directory = 'newData/dataset/all'
output_directory = 'resized_images/train/all'
normalized_images_list = []
image_paths=[os.path.join(input_directory,filename) for filename in os.listdir(input_directory)]
new_size=(224,224)
for image_path in image_paths:
    image = cv2.imread(image_path)
    if image is not None:
        resized_image = cv2.resize(image, new_size)
        # Normalize the image
        normalized_image = resized_image / 255.0
        normalized_images_list.append(normalized_image)
        # Extract the filename without extension
        filename = os.path.splitext(os.path.basename(image_path))[0]
        # Save the normalized and resized image with a new name
        output_path = os.path.join(output_directory, f'{filename}.jpg')
        cv2.imwrite(output_path, (normalized_image * 255).astype(np.uint8))
output_file_paths = [os.path.join(output_directory, f'{filename}.jpg') for filename in os.listdir(output_directory)]
np.save('processed_image_paths.npy', output_file_paths)
normalized_images_array = np.array(normalized_images_list)
print(normalized_images_array[:])
np.save('normalized_images.npy', normalized_images_array)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0